2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_setup.py:_flush():69] setting env: {'entity': 'naddeok', 'project': 'ECG Heartbeat Verifier', 'root_dir': '/home/naddeok5/HeartBreaker', 'run_id': 'gbqcmvvp', 'sweep_param_path': '/home/naddeok5/HeartBreaker/wandb/sweep-gq8mwnhp/config-gbqcmvvp.yaml', 'sweep_id': 'gq8mwnhp'}
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_setup.py:_flush():69] setting login settings: {}
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_init.py:_log_setup():336] Logging user logs to /home/naddeok5/HeartBreaker/wandb/run-20210619_135847-gbqcmvvp/logs/debug.log
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_init.py:_log_setup():337] Logging internal logs to /home/naddeok5/HeartBreaker/wandb/run-20210619_135847-gbqcmvvp/logs/debug-internal.log
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_init.py:init():369] calling init triggers
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_init.py:init():374] wandb.init called with sweep_config: {'batch_size': 57, 'criterion': 'binary_cross_entropy', 'epochs': 808, 'learning_rate': 0.0280825512956359, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': None, 'use_SAM': True, 'weight_decay': 1e-05}
config: {'epochs': 20, 'batch_size': 1, 'momentum': 0.9, 'weight_decay': 1e-05, 'learning_rate': 1e-05, 'optimizer': 'adam', 'scheduler': 'Cosine Annealing', 'criterion': 'binary_cross_entropy', 'use_SAM': True}
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [wandb_init.py:init():418] starting backend
2021-06-19 13:58:47,581 INFO    Thread-4553:2727604 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-06-19 13:58:47,583 INFO    Thread-4553:2727604 [backend.py:ensure_launched():132] starting backend process...
2021-06-19 13:58:47,619 INFO    Thread-4553:2727604 [backend.py:ensure_launched():136] started backend process with pid: 431324
2021-06-19 13:58:47,621 INFO    Thread-4553:2727604 [wandb_init.py:init():423] backend started and connected
2021-06-19 13:58:47,622 INFO    Thread-4553:2727604 [wandb_run.py:_config_callback():787] config_cb None None {'batch_size': 57, 'criterion': 'binary_cross_entropy', 'epochs': 808, 'learning_rate': 0.0280825512956359, 'momentum': 0.9, 'optimizer': 'adam', 'scheduler': None, 'use_SAM': True, 'weight_decay': 1e-05}
2021-06-19 13:58:47,623 INFO    Thread-4553:2727604 [wandb_init.py:init():465] updated telemetry
2021-06-19 13:58:47,624 INFO    Thread-4553:2727604 [wandb_init.py:init():484] communicating current version
2021-06-19 13:58:48,668 INFO    Thread-4553:2727604 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.32 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-06-19 13:58:48,668 INFO    Thread-4553:2727604 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-06-19 13:58:48,783 INFO    Thread-4553:2727604 [wandb_init.py:init():522] starting run threads in backend
2021-06-19 13:58:50,188 INFO    Thread-4553:2727604 [wandb_run.py:_console_start():1565] atexit reg
2021-06-19 13:58:50,188 INFO    Thread-4553:2727604 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-06-19 13:58:50,188 INFO    Thread-4553:2727604 [wandb_run.py:_redirect():1417] Redirecting console.
2021-06-19 13:58:50,189 ERROR   Thread-4553:2727604 [wandb_run.py:_redirect():1482] Failed to redirect.
Traceback (most recent call last):
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1475, in _redirect
    out_redir.install()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 605, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 555, in add_fd
    self._register()
  File "/home/naddeok5/.local/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 540, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/usr/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2021-06-19 13:58:50,189 INFO    Thread-4553:2727604 [wandb_init.py:init():546] run started, returning control to user process
2021-06-19 22:26:30,734 INFO    Thread-4553:2727604 [wandb_run.py:finish():1208] finishing run naddeok/ECG Heartbeat Verifier/gbqcmvvp
